name: Build and push docker image
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-source:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare sha_short variable for docker tagging
        uses: benjlevesque/short-sha@v2.1
        id: short-sha

      - name: Build image and push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.image-source }}
          tags: |
            ${{ inputs.image-name }}:${{ steps.short-sha.outputs.sha }}
            ${{ inputs.image-name }}:latest
          # build on feature branches, push only on master branch
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
